apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consensus-vision
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YunHwa0905/consensus-vision.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true      # git에서 지워진 리소스는 클러스터에서도 자동 제거
      selfHeal: true    # 클러스터를 직접 수정해도 git 상태로 자동 되돌림
    syncOptions:
      - CreateNamespace=true
