apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: consensus-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: manual
        deleteClaim: false
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
