apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: image-jobs
  namespace: kafka
  labels:
    strimzi.io/cluster: consensus-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
