apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: consensus-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: consensus
            - name: DB_USER
              valueFrom:
                secretKeyRef: { name: mysql-secret, key: username }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: mysql-secret, key: password }
            - name: UPLOAD_DIR
              value: /data/uploads
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: consensus-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
          volumeMounts:
            - name: uploads-storage
              mountPath: /data/uploads
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
